node:
  id: id_1
  cluster: service1
dynamic_resources:
  lds_config:
    path: "/work/envoy-config/lds.yaml"
  cds_config:
    path: "/work/envoy-config/cds.yaml"
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
